'use client';

import {CalendarDays,ChevronRight,FileText,FolderKanban,GripVertical,Image,MessageSquare,ReceiptText,Route,Send,Users,X} from 'lucide-react';
import {useState} from 'react';
import type {PointerEvent} from 'react';
import type {RecordItem} from '@/lib/model';
import {money} from '@/lib/model';

type QuickAccess='project'|'messages'|'plans'|'documents'|'agenda'|'photos';
type Props={client:RecordItem;records:RecordItem[];onOpen:(id:string)=>void;onMessage:()=>void;onSendMessage:(body:string)=>void};
const title=(record:RecordItem)=>record.data.title||record.data.number||record.data.name||'Élément du dossier';
const date=(value:string)=>value?new Intl.DateTimeFormat('fr-CA',{day:'numeric',month:'short'}).format(new Date(`${value}T12:00:00`)):'';

export default function ClientCockpit({client,records,onOpen,onMessage,onSendMessage}:Props){
 const related=records.filter(record=>record.client_id===client.id);
 const projects=related.filter(record=>record.kind==='project');const tasks=related.filter(record=>record.kind==='task');const visits=related.filter(record=>record.kind==='visit');const quotes=related.filter(record=>record.kind==='quote');const invoices=related.filter(record=>record.kind==='invoice');const docs=related.filter(record=>record.kind==='document');const messages=related.filter(record=>record.kind==='message'&&record.data.visibility!=='internal').sort((a,b)=>a.created_at.localeCompare(b.created_at));
 const done=tasks.filter(task=>task.data.status==='Validée').length;const progress=tasks.length?Math.round(done/tasks.length*100):projects.length?Math.round(projects.reduce((sum,project)=>sum+Number(project.data.progress||0),0)/projects.length):0;const nextVisit=visits.filter(visit=>visit.data.date||visit.data.start).sort((a,b)=>String(a.data.date||a.data.start).localeCompare(String(b.data.date||b.data.start)))[0];const nextTask=tasks.find(task=>task.data.status!=='Validée');const outstanding=invoices.filter(invoice=>invoice.data.status!=='Payée').reduce((sum,invoice)=>sum+Number(invoice.data.totals?.total||0),0);
 const [quick,setQuick]=useState<QuickAccess|null>(null);const [messageBody,setMessageBody]=useState('');const [position,setPosition]=useState({x:0,y:0});const [drag,setDrag]=useState<{x:number;y:number;left:number;top:number}|null>(null);
 const planProject=projects.find(project=>project.data.plan);const photos=docs.filter(doc=>String(doc.data.mime||'').startsWith('image/'));
 const quickCopy=quick==='project'?{label:'PROJET',title:projects[0]?title(projects[0]):'Projet à créer',detail:projects[0]?`${projects.length} projet${projects.length>1?'s':''} dans ce dossier.`:'Créez le projet pour centraliser les plans, tâches et documents.'}:quick==='plans'?{label:'PLANS 2D / 3D',title:planProject?.data.plan?.validated?'Plan validé et partageable':'Espace plans',detail:planProject?'Ouvrez le plan pour le modifier, le visualiser en 3D ou le partager.':'Ajoutez un plan depuis le projet afin de le préparer et le partager.'}:quick==='documents'?{label:'DOCUMENTS',title:docs.length?`${docs.length} document${docs.length>1?'s':''} disponible${docs.length>1?'s':''}`:'Documents du dossier',detail:docs.length?'Consultez les plans, devis et pièces partagées.':'Ajoutez des documents au projet ou au dossier client.'}:quick==='agenda'?{label:'AGENDA',title:nextVisit?title(nextVisit):'Aucun rendez-vous prévu',detail:nextVisit?`Prochain rendez-vous : ${date(nextVisit.data.date||nextVisit.data.start)}.`:'Planifiez une visite ou un rendez-vous avec le client.'}:quick==='photos'?{label:'PHOTOS',title:photos.length?`${photos.length} photo${photos.length>1?'s':''}`:'Photos du dossier',detail:photos.length?'Ouvrez les photos prises pendant la visite.':'Ajoutez des photos à la visite ou aux documents.'}:null;
 function openQuick(){const target=quick==='project'?projects[0]:quick==='plans'?planProject||projects[0]:quick==='documents'?docs[0]||projects[0]:quick==='agenda'?nextVisit||visits[0]||projects[0]:quick==='photos'?photos[0]||docs[0]||projects[0]:undefined;if(target)onOpen(target.id);setQuick(null)}
 function sendFromCockpit(event:React.FormEvent){event.preventDefault();const body=messageBody.trim();if(!body)return;onSendMessage(body);setMessageBody('')}
 function startDrag(event:PointerEvent<HTMLElement>){if(window.matchMedia('(max-width:640px)').matches)return;event.currentTarget.setPointerCapture(event.pointerId);setDrag({x:event.clientX,y:event.clientY,left:position.x,top:position.y})}
 function moveDrag(event:PointerEvent<HTMLElement>){if(!drag)return;setPosition({x:Math.max(-340,Math.min(340,drag.left+event.clientX-drag.x)),y:Math.max(-210,Math.min(210,drag.top+event.clientY-drag.y))})}
 function endDrag(){setDrag(null)}
 return <section className="client-cockpit">
  <header className="client-cockpit-head"><div className="client-avatar-large">{String(client.data.name||'?').slice(0,1).toUpperCase()}</div><div className="client-identity"><p className="eyebrow">ESPACE CLIENT · VUE ADMIN</p><h2>{client.data.name}</h2><div className="client-contacts"><a href={`mailto:${client.data.email||''}`}>{client.data.email||'Courriel à ajouter'}</a><a href={`tel:${client.data.phone||''}`}>{client.data.phone||'Téléphone à ajouter'}</a><span>{client.data.address||'Adresse à ajouter'}</span></div></div><div className="client-head-actions"><button className="btn primary" onClick={()=>setQuick('messages')}><MessageSquare size={17}/>Message au client</button><a className="btn secondary" href={`tel:${client.data.phone||''}`}><Users size={17}/>Appeler</a></div></header>
  <div className="client-progress"><div><p className="eyebrow">AVANCEMENT GLOBAL</p><strong>{progress}%</strong><span>{projects.length?projects[0].data.status||'Projet à planifier':'Dossier à planifier'}</span></div><div className="progress-track" aria-label={`${progress}% du projet terminé`}><span style={{width:`${progress}%`}}/></div><div className="progress-copy"><b>{done} tâche{done>1?'s':''} validée{done>1?'s':''}</b><small>{nextTask?`À suivre : ${title(nextTask)}`:'Aucune tâche en attente'}</small></div></div>
  <nav className="client-hub-nav" aria-label="Accès rapide au dossier"><button onClick={()=>setQuick('project')}><FolderKanban size={17}/>Projet <span>{projects.length}</span></button><button onClick={()=>setQuick('messages')}><MessageSquare size={17}/>Messages <span>{messages.length}</span></button><button onClick={()=>setQuick('plans')}><Route size={17}/>Plans 2D / 3D <span>{projects.filter(project=>project.data.plan).length}</span></button><button onClick={()=>setQuick('documents')}><FileText size={17}/>Documents <span>{docs.length}</span></button><button onClick={()=>setQuick('agenda')}><CalendarDays size={17}/>Agenda <span>{visits.length}</span></button><button onClick={()=>setQuick('photos')}><Image size={17}/>Photos <span>{photos.length}</span></button></nav>
  {quick==='messages'?<section className="client-chat-popover" aria-label="Conversation avec le client" style={{transform:`translate(${position.x}px,${position.y}px)`}} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}><header onPointerDown={startDrag}><GripVertical className="client-chat-grip" size={18}/><div><p className="eyebrow">CONVERSATION PRIVÉE</p><b>{client.data.name}</b><small>{messages.length} message{messages.length>1?'s':''} dans ce dossier</small></div><button type="button" className="client-quick-close" aria-label="Fermer la conversation" onPointerDown={event=>event.stopPropagation()} onClick={()=>setQuick(null)}><X size={16}/></button></header><div className="client-chat-list">{messages.slice(-4).map(message=><div key={message.id} className={`client-chat-message ${message.data.sender_id==='demo-user'?'own':''}`}><small>{message.data.sender} · {new Date(message.created_at).toLocaleString('fr-CA',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})}</small><p>{message.data.body}</p></div>)}{!messages.length&&<p className="client-chat-empty">Commencez la conversation avec le client.</p>}</div><form onSubmit={sendFromCockpit}><textarea aria-label="Votre message au client" value={messageBody} onChange={event=>setMessageBody(event.target.value)} placeholder="Écrire un message…" maxLength={10000} required/><button type="submit" aria-label="Envoyer le message"><Send size={18}/></button></form><footer><button type="button" onClick={onMessage}>Ouvrir la messagerie complète <ChevronRight size={16}/></button></footer></section>:quick&&quickCopy&&<div className="client-quick-popover" role="status"><button type="button" className="client-quick-close" aria-label="Fermer l’aperçu" onClick={()=>setQuick(null)}><X size={16}/></button><div><p className="eyebrow">{quickCopy.label}</p><b>{quickCopy.title}</b><p>{quickCopy.detail}</p></div><button type="button" className="client-quick-open" aria-label={`Ouvrir ${quickCopy.title}`} onClick={openQuick}><ChevronRight size={22}/></button></div>}
  <div className="client-hub-grid"><section><div className="hub-title"><h3>À faire maintenant</h3><span>{nextTask?'Action requise':'À jour'}</span></div>{nextTask?<button className="client-action-row" onClick={()=>onOpen(nextTask.id)}><div><b>{title(nextTask)}</b><small>{nextTask.data.status} · {nextTask.data.due?`échéance ${date(nextTask.data.due)}`:'échéance à définir'}</small></div><ChevronRight size={18}/></button>:<p className="hub-empty">Aucune action en attente pour ce dossier.</p>}{nextVisit&&<button className="client-action-row" onClick={()=>onOpen(nextVisit.id)}><CalendarDays size={18}/><div><b>Prochain rendez-vous</b><small>{title(nextVisit)} · {date(nextVisit.data.date||nextVisit.data.start)}</small></div><ChevronRight size={18}/></button>}</section><section><div className="hub-title"><h3>Projets & plans</h3><span>{projects.length}</span></div>{projects.map(project=><button className="client-project-row" key={project.id} onClick={()=>onOpen(project.id)}><div><b>{title(project)}</b><small>{project.data.status||'À planifier'} {project.data.plan?.validated?'· Plan 2D / 3D prêt':''}</small></div><span>{project.data.plan?.validated?'Plan partagé':'Ouvrir'}</span><ChevronRight size={18}/></button>)}{!projects.length&&<p className="hub-empty">Créez un projet depuis les actions du dossier.</p>}</section><section><div className="hub-title"><h3>Finances du dossier</h3><ReceiptText size={18}/></div><div className="client-money"><span>Devis</span><b>{quotes.length}</b><span>Factures à recevoir</span><b>{money(outstanding)}</b></div>{quotes.slice(0,2).map(quote=><button className="client-finance-row" key={quote.id} onClick={()=>onOpen(quote.id)}><span>{title(quote)}</span><small>{quote.data.status}</small></button>)}</section></div>
 </section>;
}
