'use client';

import {CalendarDays,ChevronRight,FileText,FolderKanban,Image,MessageSquare,ReceiptText,Route,Users} from 'lucide-react';
import type {RecordItem} from '@/lib/model';
import {money} from '@/lib/model';

type Props={client:RecordItem;records:RecordItem[];onOpen:(id:string)=>void;onMessage:()=>void};
const title=(record:RecordItem)=>record.data.title||record.data.number||record.data.name||'Élément du dossier';
const date=(value:string)=>value?new Intl.DateTimeFormat('fr-CA',{day:'numeric',month:'short'}).format(new Date(`${value}T12:00:00`)):'';

export default function ClientCockpit({client,records,onOpen,onMessage}:Props){
 const related=records.filter(record=>record.client_id===client.id);
 const projects=related.filter(record=>record.kind==='project');const tasks=related.filter(record=>record.kind==='task');const visits=related.filter(record=>record.kind==='visit');const quotes=related.filter(record=>record.kind==='quote');const invoices=related.filter(record=>record.kind==='invoice');const docs=related.filter(record=>record.kind==='document');const messages=related.filter(record=>record.kind==='message'&&record.data.visibility!=='internal');
 const done=tasks.filter(task=>task.data.status==='Validée').length;const progress=tasks.length?Math.round(done/tasks.length*100):projects.length?Math.round(projects.reduce((sum,project)=>sum+Number(project.data.progress||0),0)/projects.length):0;const nextVisit=visits.filter(visit=>visit.data.date||visit.data.start).sort((a,b)=>String(a.data.date||a.data.start).localeCompare(String(b.data.date||b.data.start)))[0];const nextTask=tasks.find(task=>task.data.status!=='Validée');const outstanding=invoices.filter(invoice=>invoice.data.status!=='Payée').reduce((sum,invoice)=>sum+Number(invoice.data.totals?.total||0),0);
 return <section className="client-cockpit"><header className="client-cockpit-head"><div className="client-avatar-large">{String(client.data.name||'?').slice(0,1).toUpperCase()}</div><div className="client-identity"><p className="eyebrow">ESPACE CLIENT · VUE ADMIN</p><h2>{client.data.name}</h2><div className="client-contacts"><a href={`mailto:${client.data.email||''}`}>{client.data.email||'Courriel à ajouter'}</a><a href={`tel:${client.data.phone||''}`}>{client.data.phone||'Téléphone à ajouter'}</a><span>{client.data.address||'Adresse à ajouter'}</span></div></div><div className="client-head-actions"><button className="btn primary" onClick={onMessage}><MessageSquare size={17}/>Message au client</button><a className="btn secondary" href={`tel:${client.data.phone||''}`}><Users size={17}/>Appeler</a></div></header>
  <div className="client-progress"><div><p className="eyebrow">AVANCEMENT GLOBAL</p><strong>{progress}%</strong><span>{projects.length?projects[0].data.status||'Projet à planifier':'Dossier à planifier'}</span></div><div className="progress-track" aria-label={`${progress}% du projet terminé`}><span style={{width:`${progress}%`}}/></div><div className="progress-copy"><b>{done} tâche{done>1?'s':''} validée{done>1?'s':''}</b><small>{nextTask?`À suivre : ${title(nextTask)}`:'Aucune tâche en attente'}</small></div></div>
  <nav className="client-hub-nav" aria-label="Accès rapide au dossier"><button onClick={()=>projects[0]&&onOpen(projects[0].id)}><FolderKanban size={17}/>Projet <span>{projects.length}</span></button><button onClick={onMessage}><MessageSquare size={17}/>Messages <span>{messages.length}</span></button><button onClick={()=>projects.find(project=>project.data.plan)&&onOpen(projects.find(project=>project.data.plan)!.id)}><Route size={17}/>Plans 2D / 3D <span>{projects.filter(project=>project.data.plan).length}</span></button><button onClick={()=>docs[0]&&onOpen(docs[0].id)}><FileText size={17}/>Documents <span>{docs.length}</span></button><button onClick={()=>visits[0]&&onOpen(visits[0].id)}><CalendarDays size={17}/>Agenda <span>{visits.length}</span></button><button onClick={()=>docs.find(doc=>String(doc.data.mime||'').startsWith('image/'))&&onOpen(docs.find(doc=>String(doc.data.mime||'').startsWith('image/'))!.id)}><Image size={17}/>Photos <span>{docs.filter(doc=>String(doc.data.mime||'').startsWith('image/')).length}</span></button></nav>
  <div className="client-hub-grid"><section><div className="hub-title"><h3>À faire maintenant</h3><span>{nextTask?'Action requise':'À jour'}</span></div>{nextTask?<button className="client-action-row" onClick={()=>onOpen(nextTask.id)}><div><b>{title(nextTask)}</b><small>{nextTask.data.status} · {nextTask.data.due?`échéance ${date(nextTask.data.due)}`:'échéance à définir'}</small></div><ChevronRight size={18}/></button>:<p className="hub-empty">Aucune action en attente pour ce dossier.</p>}{nextVisit&&<button className="client-action-row" onClick={()=>onOpen(nextVisit.id)}><CalendarDays size={18}/><div><b>Prochain rendez-vous</b><small>{title(nextVisit)} · {date(nextVisit.data.date||nextVisit.data.start)}</small></div><ChevronRight size={18}/></button>}</section><section><div className="hub-title"><h3>Projets & plans</h3><span>{projects.length}</span></div>{projects.map(project=><button className="client-project-row" key={project.id} onClick={()=>onOpen(project.id)}><div><b>{title(project)}</b><small>{project.data.status||'À planifier'} {project.data.plan?.validated?'· Plan 2D / 3D prêt':''}</small></div><span>{project.data.plan?.validated?'Plan partagé':'Ouvrir'}</span><ChevronRight size={18}/></button>)}{!projects.length&&<p className="hub-empty">Créez un projet depuis les actions du dossier.</p>}</section><section><div className="hub-title"><h3>Finances du dossier</h3><ReceiptText size={18}/></div><div className="client-money"><span>Devis</span><b>{quotes.length}</b><span>Factures à recevoir</span><b>{money(outstanding)}</b></div>{quotes.slice(0,2).map(quote=><button className="client-finance-row" key={quote.id} onClick={()=>onOpen(quote.id)}><span>{title(quote)}</span><small>{quote.data.status}</small></button>)}</section></div>
 </section>;
}
