'use client';
import {useState} from 'react';
import {Download,Send} from 'lucide-react';
import {Data,RecordItem,money} from '@/lib/model';
import {financialOverview,financialYears,expenseTotal} from '@/lib/financial-overview';
import Dashboard from './ui/dashboard-4';
import {useRef} from 'react';

type Person={id:string;name:string;role:string};
type Props={records:RecordItem[];users:Person[];settings:Data;demo:boolean;onDownload:(blob:Blob,name:string)=>void;onMessage:(message:string)=>void};
export default function FinancialOverview({records,users,settings,demo,onDownload,onMessage}:Props){
 const years=financialYears(records),[year,setYear]=useState(new Date().getFullYear());
 const [clientId,setClientId]=useState(''),[projectId,setProjectId]=useState('');
 const [exportOpen,setExportOpen]=useState(false);const exportRef=useRef<HTMLDetailsElement>(null);
 const [exportScope,setExportScope]=useState<'company'|'client'|'partner'>('company'),[partnerId,setPartnerId]=useState('');
 const [from,setFrom]=useState(`${year}-01-01`),[to,setTo]=useState(`${year}-12-31`),[emails,setEmails]=useState(''),[busy,setBusy]=useState(false);
 const clients=records.filter(record=>record.kind==='client'&&!record.data.deleted_at),projects=records.filter(record=>record.kind==='project'&&(!clientId||record.client_id===clientId));
 const stats=financialOverview(records,year,clientId,projectId);
 const categoryTotals=new Map<string,number>();for(const record of records){if(record.kind==='expense'&&record.data.posted&&String(record.data.date||record.created_at).startsWith(String(year))&&(!clientId||record.client_id===clientId)&&(!projectId||record.project_id===projectId)){const key=String(record.data.category||'Autre');categoryTotals.set(key,(categoryTotals.get(key)||0)+expenseTotal(record.data))}}
 const categories=[...categoryTotals].map(([name,amount])=>({name,amount})).sort((a,b)=>b.amount-a.amount);
 const download=async()=>{setBusy(true);try{if(demo){const {default:JSZip}=await import('jszip');const zip=new JSZip();zip.file('DEMONSTRATION.txt','Données fictives du tableau de bord MG Pro. Aucun justificatif réel dans cette archive.');zip.file('resume.csv',`Année;Client;Projet;Facturé;Encaissé;Dépenses\n${year};${clientId};${projectId};${stats.billed};${stats.paid};${stats.spent}\n`);onDownload(await zip.generateAsync({type:'blob'}),'mgpro-demonstration.zip');return;}const params=new URLSearchParams({from,to,scope:exportScope});if(exportScope==='client'&&clientId)params.set('client_id',clientId);if(exportScope==='client'&&projectId)params.set('project_id',projectId);if(exportScope==='partner'&&partnerId)params.set('partner_id',partnerId);const res=await fetch('/api/accounting/bundle?'+params);if(!res.ok){const body=await res.json();throw new Error(body.error||'Export impossible.');}onDownload(await res.blob(),`mgpro-comptabilite-${from}-${to}.zip`);onMessage('Dossier comptable téléchargé.')}catch(error){onMessage((error as Error).message)}finally{setBusy(false)}};
 const send=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);try{if(demo){onMessage('Démonstration : aucun courriel envoyé.');return;}const res=await fetch('/api/accounting/bundle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from,to,scope:exportScope,client_id:exportScope==='client'?clientId:undefined,project_id:exportScope==='client'?projectId:undefined,partner_id:exportScope==='partner'?partnerId:undefined,emails})});const body=await res.json();if(!res.ok)throw new Error(body.error||'Envoi impossible.');onMessage('Dossier comptable transmis au service de courriel.')}catch(error){onMessage((error as Error).message)}finally{setBusy(false)}};
 return <section className="financial-overview panel"><header><div><p className="eyebrow">SUIVI FINANCIER</p><h2>Vue d’ensemble financière</h2><p>Par année, client et projet. Les montants proviennent des documents enregistrés.</p></div><div className="financial-filters"><label>Année<select value={year} onChange={event=>{const next=Number(event.target.value);setYear(next);setFrom(`${next}-01-01`);setTo(`${next}-12-31`);}}>{years.map(item=><option key={item}>{item}</option>)}</select></label><label>Client<select value={clientId} onChange={event=>{setClientId(event.target.value);setProjectId('');}}><option value="">Toute l’entreprise</option>{clients.map(client=><option key={client.id} value={client.id}>{client.data.name}</option>)}</select></label><label>Projet<select value={projectId} disabled={!clientId} onChange={event=>setProjectId(event.target.value)}><option value="">Tous les projets</option>{projects.map(project=><option key={project.id} value={project.id}>{project.data.title}</option>)}</select></label></div></header>
 <Dashboard data={{stats,categories,year,onExport:()=>{setExportOpen(true);requestAnimationFrame(()=>exportRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'}))}}}/>
 <details ref={exportRef} className="financial-export" open={exportOpen} onToggle={event=>setExportOpen(event.currentTarget.open)}><summary>Exporter la comptabilité et les justificatifs</summary><div className="financial-export-body"><div className="financial-filters"><label>Type de dossier<select value={exportScope} onChange={event=>setExportScope(event.target.value as 'company'|'client'|'partner')}><option value="company">Toute l’entreprise</option><option value="client">Un client</option><option value="partner">Un prestataire</option></select></label>{exportScope==='client'&&<label>Client du dossier<select value={clientId} onChange={event=>{setClientId(event.target.value);setProjectId('')}}><option value="">Choisir un client</option>{clients.map(client=><option key={client.id} value={client.id}>{client.data.name}</option>)}</select></label>}{exportScope==='partner'&&<label>Prestataire<select value={partnerId} onChange={event=>setPartnerId(event.target.value)} required><option value="">Choisir</option>{users.filter(person=>person.role==='worker').map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</select></label>}<label>Du<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Au<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label></div><p>Le ZIP regroupe le rapport de période, le journal, les factures, les dépenses et leurs pièces disponibles.</p><button type="button" className="btn secondary" disabled={busy||exportScope==='client'&&!clientId||exportScope==='partner'&&!partnerId} onClick={()=>void download()}><Download size={16}/>Télécharger le dossier ZIP</button><form onSubmit={event=>void send(event)}><label>Destinataires du courriel<input type="text" value={emails} onChange={event=>setEmails(event.target.value)} placeholder="comptable@exemple.com, direction@exemple.com" required/></label><button className="btn secondary" disabled={busy||exportScope==='client'&&!clientId||exportScope==='partner'&&!partnerId}><Send size={16}/>Envoyer le dossier</button></form></div></details></section>;
}
