'use client';
import {useEffect,useState} from 'react';
import {Bell,Check,RefreshCw} from 'lucide-react';
import type {RecordItem} from '@/lib/model';
type Event={id:string;recordId:string;kind:string;title:string;action:string;date:string;read:boolean};
const labels:Record<string,string>={user_save:'Dossier enregistré',issue:'Facture émise',payment:'Paiement enregistré',credit:'Avoir enregistré',post:'Dépense comptabilisée',pay:'Dépense réglée',send:'Document envoyé',sent:'Document envoyé'};
export default function NotificationCentre({demo,records,onOpen}:{demo:boolean;records:RecordItem[];onOpen:(id:string)=>void}){
 const [rows,setRows]=useState<Event[]>([]),[filter,setFilter]=useState('Toutes'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){setBusy(true);setError('');try{if(demo){setRows(old=>records.filter(x=>!['settings','client'].includes(x.kind)).map(x=>({id:x.id,recordId:x.id,kind:x.kind,title:x.data.title||x.data.name||x.data.number||'Dossier',action:'user_save',date:x.updated_at,read:old.find(o=>o.id===x.id)?.read||false})));return}const response=await fetch('/api/notifications',{cache:'no-store'}),body=await response.json();if(!response.ok)throw new Error(body.error);setRows(body.notifications)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void refresh();if(demo)return;const timer=setInterval(()=>void refresh(),30000);return()=>clearInterval(timer)},[demo]);
 async function mark(ids:string[]){setError('');try{if(!demo){const response=await fetch('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})});const body=await response.json();if(!response.ok)throw new Error(body.error)}setRows(old=>old.map(x=>ids.includes(x.id)?{...x,read:true}:x))}catch(e){setError((e as Error).message)}}
 const unread=rows.filter(x=>!x.read),shown=rows.filter(x=>filter==='Toutes'||!x.read);
 return <section className="module-centre"><div className="module-section-heading"><div><h2>Notifications <span className="badge">{unread.length} non lues</span></h2><p>{demo?'Historique de démonstration, sans enregistrement serveur.':'Historique des actions enregistrées. Votre lecture est conservée pour votre compte.'}</p></div><div className="module-actions"><button className="btn secondary" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/>Actualiser</button><button className="btn secondary" disabled={!unread.length} onClick={()=>void mark(unread.map(x=>x.id))}><Check size={16}/>Tout marquer comme lu</button></div></div><div className="module-actions">{['Toutes','Non lues'].map(x=><button className="btn secondary" key={x} aria-pressed={filter===x} onClick={()=>setFilter(x)}>{x}</button>)}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="notification-history">{shown.map(event=><article key={event.id} className={event.read?'read':'unread'}><span className="notification-symbol"><Bell size={19}/></span><div><small>{labels[event.action]||'Action enregistrée'} · {event.kind}</small><h3>{event.title}</h3><time>{new Date(event.date).toLocaleString('fr-CA')}</time></div><div className="module-actions"><button className="btn ghost" onClick={()=>{void mark([event.id]);onOpen(event.recordId)}}>Consulter</button>{!event.read&&<button className="icon-button" aria-label={`Marquer ${event.title} comme lu`} onClick={()=>void mark([event.id])}><Check size={17}/></button>}</div></article>)}</div>{!shown.length&&!busy&&<div className="module-empty"><Bell/><h3>{filter==='Toutes'?'Aucune notification':'Vous êtes à jour'}</h3></div>}</section>
}
