 'use client';
import {useEffect,useState} from 'react';
import {fromRooms,planSchema,type Plan} from '@/lib/plan';
import type {RecordItem,Data} from '@/lib/model';
import PlanEditor from './plan-editor';
import PlanInvitations from './plan-invitations';
export default function ProjectPlan({record,visits,documents,email,demo,userId,onSave,onUpload}:{record:RecordItem;visits:RecordItem[];documents:RecordItem[];email:string;demo:boolean;userId:string;onSave:(data:Data)=>Promise<RecordItem>;onUpload:(file:File)=>Promise<void>}){
 const [plan,setPlan]=useState<Plan|null>(record.data.plan||null),[open,setOpen]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[recovery,setRecovery]=useState<Plan|null>(null),[saved,setSaved]=useState(!!record.data.plan);const key=`mgpro-project-plan-${userId}-${record.id}`;
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const d=JSON.parse(raw);if(planSchema.safeParse(d).success)setRecovery(d)}}catch{}},[key]);
 function change(p:Plan){setPlan(p);setSaved(false);try{localStorage.setItem(key,JSON.stringify(p));setMessage('Modifications conservées sur cet appareil. Enregistrez le plan pour le partager.')}catch{setMessage('Stockage local indisponible. Enregistrez avant de quitter.')}}
 async function persist(){if(!plan)return;setBusy(true);try{await onSave({...record.data,plan});localStorage.removeItem(key);setRecovery(null);setSaved(true);setMessage('Plan enregistré dans le projet. Vous pouvez le rouvrir à tout moment.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 const pdfs=documents.filter(d=>d.data.mime==='application/pdf');
 return <section className="panel"><div className="panel-title"><h2>Plans du projet · 2D & 3D</h2></div><div className="detail-body"><p>Retrouvez le plan du projet, même après la visite. Joignez votre PDF comme référence et ouvrez la maquette 3D enregistrée.</p><label className="upload-button">Ajouter le PDF du plan<input type="file" accept="application/pdf" disabled={busy||demo} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{if(file.size>4*1024*1024)throw Error('Le PDF doit faire moins de 4 Mo.');await onUpload(file);setMessage('PDF conservé pour transfert. Il apparaîtra ci-dessous une fois transféré.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false);e.target.value=''}}}/></label>{pdfs.map(d=><p key={d.id}><a href={'/api/documents?id='+d.id} target="_blank" rel="noreferrer">Ouvrir {d.data.name}</a></p>)}<p className="muted">Le PDF reste un document de référence : il n’est pas converti automatiquement en géométrie 3D. Reprenez le relevé d’une visite ou renseignez les pièces et dimensions dans l’éditeur.</p>{recovery&&<button className="btn secondary" onClick={()=>{setPlan(recovery);setSaved(false);setRecovery(null);setOpen(true)}}>Reprendre les modifications non enregistrées</button>}{!plan&&<div className="button-row"><button className="btn secondary" onClick={()=>{change(fromRooms([{name:'Pièce',length:0,width:0,height:0,unit:'m'}]));setOpen(true)}}>Créer le plan 2D</button>{visits.filter(v=>v.data.plan).map(v=><button className="btn secondary" key={v.id} onClick={()=>{change(structuredClone(v.data.plan));setOpen(true)}}>Reprendre le plan : {v.data.title}</button>)}</div>}{plan&&<><div className="button-row"><button className="btn primary" onClick={()=>setOpen(!open)}>{open?'Fermer la visualisation':plan.validated?'Visualiser en 3D':'Ouvrir le plan 2D'}</button><button className="btn secondary" disabled={busy||!planSchema.safeParse(plan).success} onClick={persist}>Enregistrer le plan dans le projet</button></div>{open&&<PlanEditor value={plan} onChange={change} initialView="design"/>}{saved&&plan.validated&&<PlanInvitations id={record.id} email={email} demo={demo}/>}</>}{message&&<p role="status">{message}</p>}</div></section>
}
