'use client';

import {useEffect,useRef} from 'react';
import {Download,FileCheck,FileText,Send,X} from 'lucide-react';
import {Data,RecordItem,money,totals} from '@/lib/model';

type Props={quote:RecordItem;client:Data;settings:Data;busy:boolean;onSave:(data:Data)=>Promise<void>|void;onClose:()=>void;onPdf:()=>void;onSend:(data:Data)=>void;error?:string;readOnly?:boolean};

export default function QuoteStudio({quote,client,busy,onClose,onPdf,onSend,error,readOnly=false}:Props){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ref.current?.showModal();const root=document.documentElement,previous=root.style.overflow;root.style.overflow='hidden';return()=>{ref.current?.close();root.style.overflow=previous}},[]);
 const data=quote.data,summary=totals(data),change=Boolean(data.document_type==='change_order'||data.change_order),label=change?'Ordre de changement':'Contrat / soumission';
 return <dialog ref={ref} className="app-dialog wide contract-preview-dialog" onCancel={onClose} onClick={event=>{if(event.target===ref.current)onClose()}}><header><div><p className="eyebrow">APERÇU À ENVOYER AU CLIENT</p><h2>{label}</h2><small>{data.number||'Brouillon'} · {client?.name||'Client'}</small></div><button className="icon-button" aria-label="Fermer" onClick={onClose}><X/></button></header><div className="contract-preview-body"><section className="contract-preview-hero"><div><span>Client</span><strong>{client?.name||'À préciser'}</strong><small>{client?.address||''}</small></div><div><span>Date</span><strong>{data.date||'À préciser'}</strong><small>{data.status||'Brouillon'}</small></div><div><span>Total du document</span><strong>{money(summary.total)}</strong><small>Taxes incluses</small></div></section><section className="contract-preview-section"><h3><FileText size={17}/>Prestations incluses</h3>{data.lines?.length?<div className="table-scroll"><table><thead><tr><th>Description</th><th>Quantité</th><th>Prix unitaire</th><th>Total</th></tr></thead><tbody>{data.lines.map((line:Data,index:number)=><tr key={index}><td>{line.description||'Prestation à préciser'}</td><td>{line.quantity||0} {line.unit||''}</td><td>{money(Number(line.price||0))}</td><td>{money(Number(line.quantity||0)*Number(line.price||0))}</td></tr>)}</tbody></table></div>:<p className="muted">Les prestations seront ajoutées avant l’envoi.</p>}<div className="contract-preview-totals"><span>Sous-total <b>{money(summary.subtotal)}</b></span>{summary.discount>0&&<span>Remise <b>− {money(summary.discount)}</b></span>}<span>TPS <b>{money(summary.tps)}</b></span><span>TVQ <b>{money(summary.tvq)}</b></span><strong>Total <b>{money(summary.total)}</b></strong></div></section><section className="contract-preview-section"><h3><FileCheck size={17}/>Modalités et acceptation</h3><p>{data.terms||'Les modalités seront précisées avant l’envoi du document.'}</p><p className="contract-preview-signature">La signature ou l’acceptation électronique du client confirmera son accord sur ce document.</p></section>{error&&<p className="error">{error}</p>}<footer className="contract-preview-actions"><button className="btn ghost" onClick={onClose}>Fermer</button><div>{!readOnly&&<button className="btn primary" disabled={busy} onClick={()=>onSend(data)}><Send size={16}/>Envoyer au client</button>}<button className="btn secondary" disabled={busy} onClick={onPdf}><Download size={16}/>Voir le PDF</button></div></footer></div></dialog>;
}
