'use client';
import type {Data} from '@/lib/model';
import {money} from '@/lib/model';

export default function QuoteLineDetails({line,onChange}:{line:Data;onChange:(line:Data)=>void}){
 const split=(key:string,value:string)=>{const next={...line,[key]:Number(value)||0,pricing_mode:'split'};next.price=Number(next.material_cost||0)+Number(next.labour_cost||0);onChange(next)};
 const profit=Number(line.margin||0)/(100+Number(line.margin||0))*100;
 return <div className="quote-line-details"><div className="form-grid three"><label>Calcul du prix<select value={line.pricing_mode||'unit'} onChange={e=>onChange({...line,pricing_mode:e.target.value,...(e.target.value==='split'?{material_cost:line.material_cost??line.price,labour_cost:line.labour_cost??0,price:Number(line.material_cost??line.price??0)+Number(line.labour_cost??0)}:{} )})}><option value="unit">Prix unitaire</option><option value="split">Matériaux + main-d’œuvre</option></select></label>{line.pricing_mode==='split'&&<><label>Matériaux / unité · avant taxes<input type="number" min="0" step=".01" value={line.material_cost??0} onChange={e=>split('material_cost',e.target.value)}/></label><label>Main-d’œuvre / unité · avant taxes<input type="number" min="0" step=".01" value={line.labour_cost??0} onChange={e=>split('labour_cost',e.target.value)}/></label></>}</div><div className="form-grid"><label>Marge de profit cible (%)<input type="number" min="0" max="99.99" step=".01" value={Math.round(profit*100)/100} onChange={e=>{const value=Math.min(99.99,Math.max(0,Number(e.target.value)||0));onChange({...line,margin:value/(100-value)*100})}}/></label><p className="muted">Coût unitaire : {money(Number(line.price||0))} · Prix avec profit : {money(Number(line.price||0)*(1+Number(line.margin||0)/100))}. Une marge de 20 % correspond à une majoration de 25 %.</p></div><label>Note pour le document client<textarea value={line.notes||''} onChange={e=>onChange({...line,notes:e.target.value})}/></label><label className="note-visibility"><input type="checkbox" checked={line.show_notes!==false} onChange={e=>onChange({...line,show_notes:e.target.checked})}/>Afficher cette note au client dans l’aperçu et le PDF</label><div className="private-note"><label>Note interne · équipe et prestataires autorisés · invisible aux clients<textarea value={line.internal_notes||''} onChange={e=>onChange({...line,internal_notes:e.target.value})}/></label><label>Note confidentielle · administration uniquement<textarea value={line.admin_notes||''} onChange={e=>onChange({...line,admin_notes:e.target.value})}/></label></div></div>;
}
