import Decimal from 'decimal.js';
export type Role = 'admin'|'worker'|'client';
export type Kind = 'client'|'request'|'project'|'task'|'visit'|'quote'|'invoice'|'expense'|'message'|'document'|'settings'|'journal';
export type Data = Record<string, any>;
export type RecordItem = {id:string;kind:Kind;client_id:string|null;project_id:string|null;data:Data;version:number;created_at:string;updated_at:string};
export type Profile = {id:string;name:string;email:string;role:Role;client_id:string|null};
export const kinds:Kind[]=['client','request','project','task','visit','quote','invoice','expense','message','document','settings','journal'];
export const round=(n:number)=>new Decimal(n).toDecimalPlaces(2,Decimal.ROUND_HALF_UP).toNumber();
export const money=(n:number)=>new Intl.NumberFormat('fr-CA',{style:'currency',currency:'CAD',maximumFractionDigits:2}).format(n||0);
export function totals(data:Data){const cent=(n:Decimal)=>n.toDecimalPlaces(2,Decimal.ROUND_HALF_UP);const subtotal=(data.lines||[]).reduce((s:Decimal,l:Data)=>s.plus(cent(new Decimal(l.quantity||0).times(l.price||0))),new Decimal(0));const discount=cent(subtotal.times(data.discount||0).div(100));const net=subtotal.minus(discount);const tps=cent(net.times(data.tps??5).div(100));const tvq=cent(net.times(data.tvq??9.975).div(100));return {subtotal:subtotal.toNumber(),discount:discount.toNumber(),net:net.toNumber(),tps:tps.toNumber(),tvq:tvq.toNumber(),total:net.plus(tps).plus(tvq).toNumber()};}
export const statuses:Record<string,string[]>={request:['Nouvelle','À contacter','Visite planifiée','Devis envoyé','Gagnée','Perdue'],project:['Planifié','En cours','En pause','Terminé'],task:['À faire','En cours','À valider','Validée'],quote:['Brouillon','Validé','Envoyé','Accepté','Refusé'],invoice:['Brouillon','Émise','Partiellement payée','Payée'],visit:['En cours','Validée']};
export const defaults={name:'Rénovations MG Pro',phone:'514-317-6305',email:'info@renovationsmgpro.com',address:'Laval, Québec',rbq:'5720-7359-01',tps:5,tvq:9.975,tps_number:'',tvq_number:'',accountant:'',seo_title:'Rénovations MG Pro | Rénovation à Laval et Montréal',seo_description:'Rénovations de cuisines, salles de bain, sous-sols et agrandissements à Laval, Montréal et sur la Rive-Nord. Demandez votre soumission.',terms:'Soumission valable 30 jours. Travaux supplémentaires soumis à une approbation écrite. Échéancier et modalités de paiement à convenir avant le début du chantier.'};
export function permitted(role:Role,kind:Kind){return role==='admin'||(role==='worker'&&['project','task','document'].includes(kind))||(role==='client'&&['client','project','quote','invoice','message','document'].includes(kind));}
