import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
import {Data,defaults,totals,money} from './model';
export async function makePdf(title:string,data:Data,client:Data={},settings:Data=defaults,photos:{bytes:Uint8Array;mime:string;caption:string}[]=[]){const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page=pdf.addPage([595,842]);let y=790;const clean=(s:any)=>String(s??'').replace(/[\u202f\u00a0]/g,' ').replace(/[–—]/g,'-').replace(/[^\x20-\x7e\xa0-\xff\n]/g,'');const line=(text:string,size=10,strong=false)=>{const words=clean(text).split(/\s+/);let current='';const draw=()=>{if(y<55){page=pdf.addPage([595,842]);y=790;}page.drawText(current,{x:45,y,size,font:strong?bold:font,color:rgb(.10,.20,.18)});y-=size+7;};for(const w of words){if(font.widthOfTextAtSize(current+' '+w,size)>505){draw();current=w;}else current+=(current?' ':'')+w;}if(current)draw();};
line(settings.name||defaults.name,23,true);line(`${settings.address||''} | ${settings.phone||''}`);line(settings.email||'');line(`Licence RBQ : ${settings.rbq||''}`);y-=20;line(title,19,true);line(data.number||'');line(`Date : ${data.date||new Date().toISOString().slice(0,10)}`);if(client.name){y-=12;line(client.name,12,true);line(client.address||'');line(client.email||'');}y-=20;
if(data.lines){for(const l of data.lines){line(l.description,11,true);line(`${l.quantity} ${l.unit||'unité'} x ${money(Number(l.price))} = ${money(Number(l.quantity)*Number(l.price))}`);if(l.notes)line(l.notes);y-=5;}const t=totals(data);y-=12;line(`Sous-total : ${money(t.subtotal)}`);if(t.discount)line(`Remise : ${money(t.discount)}`);line(`TPS (${data.tps??5} %) : ${money(t.tps)}`);line(`TVQ (${data.tvq??9.975} %) : ${money(t.tvq)}`);line(`TOTAL : ${money(t.total)}`,16,true);if(settings.tps_number)line(`N° TPS : ${settings.tps_number}`);if(settings.tvq_number)line(`N° TVQ : ${settings.tvq_number}`);}
for(const [key,label] of [['title','Projet'],['notes','Notes'],['scope','Travaux prévus'],['constraints','Contraintes'],['materials','Matériaux'],['dimensions','Dimensions'],['conditions','Conditions'],['terms','Modalités']])if(data[key]){y-=8;line(label,11,true);line(data[key]);}
if(data.rooms)for(const room of data.rooms){line(room.name||'Pièce',12,true);line(`${room.length||0} x ${room.width||0} x ${room.height||0} ${room.unit||'pi'} ; surface : ${Number(room.length||0)*Number(room.width||0)} ${room.unit||'pi'}²`);line(room.notes||'');}
if(data.reportLines)for(const l of data.reportLines)line(l,10);
for(const p of photos){try{const img=p.mime==='image/png'?await pdf.embedPng(p.bytes):p.mime==='image/jpeg'?await pdf.embedJpg(p.bytes):null;if(!img)continue;const dims=img.scaleToFit(505,300);if(y-dims.height<70){page=pdf.addPage([595,842]);y=790;}page.drawImage(img,{x:45,y:y-dims.height,width:dims.width,height:dims.height});y-=dims.height+20;line(p.caption);}catch{line('Photo non intégrable au PDF. Consultez le dossier en ligne.');}}
const pages=pdf.getPages();pages.forEach((p,i)=>p.drawText(`${settings.name||defaults.name} | ${i+1} / ${pages.length}`,{x:45,y:25,size:8,font,color:rgb(.4,.4,.4)}));return pdf.save();}
