import {redact} from '@/lib/redact';
import {NextResponse} from 'next/server';
import {identity,db} from '@/lib/supabase';
import {visible,sameOrigin} from '@/lib/access';
import {kinds,RecordItem,totals} from '@/lib/model';
import {z} from 'zod';
const schema=z.object({id:z.string().uuid().optional(),kind:z.enum(kinds as [string,...string[]]),client_id:z.string().uuid().nullable().optional(),project_id:z.string().uuid().nullable().optional(),version:z.number().int().optional(),data:z.record(z.string(),z.unknown())});
export async function GET(){const user=await identity();if(!user)return NextResponse.json({error:'Connexion requise.'},{status:401});const {data,error}=await db().from('records').select('*').order('created_at',{ascending:false}).limit(3000);if(error)return NextResponse.json({error:'Chargement impossible.'},{status:503});const rows=[];for(const r of data||[])if(await visible(user,r))rows.push(redact(user,r));let users:any[]=[];let memberships:any[]=[];if(user.role==='admin'){users=(await db().from('profiles').select('id,name,email,role,client_id,active')).data||[];memberships=(await db().from('memberships').select('*')).data||[];}return NextResponse.json({records:rows,user,users,memberships});}
export async function POST(req:Request){if(!sameOrigin(req))return NextResponse.json({error:'Origine refusée.'},{status:403});const user=await identity();if(!user)return NextResponse.json({error:'Connexion requise.'},{status:401});const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:'Données invalides.'},{status:400});const payload=parsed.data;let old:RecordItem|null=null;if(payload.id){old=(await db().from('records').select('*').eq('id',payload.id).maybeSingle()).data;if(!old||!(await visible(user,old)))return NextResponse.json({error:'Élément inaccessible.'},{status:403});if(old.kind!==payload.kind||old.client_id!==(payload.client_id??null)||old.project_id!==(payload.project_id??null))return NextResponse.json({error:'Les liens du dossier ne peuvent pas être modifiés.'},{status:400});}
 if(user.role==='worker'){if(!old||old.kind!=='task')return NextResponse.json({error:'Accès limité aux tâches affectées au chantier.'},{status:403});const status=payload.data.status;if(!['À faire','En cours','À valider'].includes(String(status)))return NextResponse.json({error:'La validation finale appartient au dirigeant.'},{status:403});payload.data={...old.data,status,completion_note:payload.data.completion_note??old.data.completion_note,submitted_by:user.id};}
 if(user.role==='client'){if(payload.kind!=='message'||old||payload.client_id!==user.client_id)return NextResponse.json({error:'Accès refusé.'},{status:403});payload.data={body:String(payload.data.body||'').slice(0,10000),visibility:'client',sender:user.name,sender_id:user.id};}
 if(payload.kind==='message')payload.data={...payload.data,sender:user.name,sender_id:user.id};
 if(['quote','invoice'].includes(payload.kind)){const lines=payload.data.lines;if(!Array.isArray(lines)||lines.length>200||lines.some((l:any)=>!l.description||!Number.isFinite(Number(l.quantity))||Number(l.quantity)<0||!Number.isFinite(Number(l.price))||Number(l.price)<0))return NextResponse.json({error:'Vérifiez les lignes du document.'},{status:400});for(const key of ['tps','tvq','discount'])if(payload.data[key]!==undefined&&(!Number.isFinite(Number(payload.data[key]))||Number(payload.data[key])<0||Number(payload.data[key])>100))return NextResponse.json({error:'Taux invalide.'},{status:400});if(old?.kind==='invoice'&&old.data.status!=='Brouillon')return NextResponse.json({error:'Une facture émise est figée. Enregistrez un paiement ou un avoir.'},{status:409});if(payload.kind==='invoice'&&payload.data.status!=='Brouillon')return NextResponse.json({error:'Utilisez le bouton Émettre pour comptabiliser une facture.'},{status:400});payload.data={...payload.data,totals:totals(payload.data)};}
 if(payload.kind==='journal'){const entries=payload.data.entries;if(!Array.isArray(entries)||entries.length<2||entries.some((e:any)=>!e.account||Number(e.debit)<0||Number(e.credit)<0||!Number.isFinite(Number(e.debit))||!Number.isFinite(Number(e.credit)))||Math.abs(entries.reduce((n:number,e:any)=>n+Number(e.debit)-Number(e.credit),0))>0.005)return NextResponse.json({error:'L’écriture doit être équilibrée : débits = crédits.'},{status:400});if(old)return NextResponse.json({error:'Une écriture comptabilisée ne se modifie pas. Passez une contre-écriture.'},{status:409});}
 if(payload.project_id){const project=(await db().from('records').select('*').eq('id',payload.project_id).eq('kind','project').maybeSingle()).data;if(!project||!(await visible(user,project)))return NextResponse.json({error:'Projet inaccessible.'},{status:403});}
 if(payload.client_id){const client=(await db().from('records').select('id').eq('id',payload.client_id).eq('kind','client').maybeSingle()).data;if(!client)return NextResponse.json({error:'Client introuvable.'},{status:400});}
 const values={kind:payload.kind,client_id:payload.client_id??null,project_id:payload.project_id??null,data:payload.data,updated_at:new Date().toISOString(),version:(old?.version||0)+1};const query=old?db().from('records').update(values).eq('id',old.id).eq('version',payload.version??0).select().maybeSingle():db().from('records').insert(values).select().single();const {data,error}=await query;if(error)return NextResponse.json({error:'Enregistrement impossible.'},{status:503});if(!data)return NextResponse.json({error:'Ce dossier a changé. Rechargez avant de réessayer.'},{status:409});await db().from('audit_log').insert({actor_id:user.id,action:'user_save',record_id:data.id});return NextResponse.json({record:data});}

