import EnglishSite from '@/components/english-site';
import BlogContent from '@/components/blog-content';
import pages from '@/content/english.json';
import articles from '@/content/blog-en.json';
import {notFound} from 'next/navigation';
import {configured,db} from '@/lib/supabase';
import {defaults} from '@/lib/model';
function resolve(path:string[]=[]){if(!path.length)return {slug:'accueil',title:'Renovation in Laval and Montréal'};if(path.length===1&&path[0]==='about')return {slug:'a-propos',title:'About MG Pro'};if(path.length===1&&path[0]==='privacy')return {slug:'privacy',title:'Privacy'};if(path[0]==='blog'&&path.length<=2){const a=path[1]?articles.find(a=>a.slug===path[1]):null;if(path[1]&&!a)return null;return {slug:'blog',article:path[1],title:a?.title||'Renovation advice'}}if(path.length===2&&path[0]==='services'){const p=pages.find(p=>p.slug===path[1]&&p.slug!=='a-propos');if(p)return {slug:p.slug,title:p.title}}return null}
export async function generateMetadata({params}:{params:Promise<{path?:string[]}>}){const {path=[]}=await params;const p=resolve(path);const canonical='/en'+(path.length?'/'+path.join('/'):'');const fr=canonical==='/en'?'/':canonical.slice(3).replace('/about','/a-propos').replace('/privacy','/confidentialite').replace('/blog','/blogue');return {title:p?.title,description:'MG Pro residential and commercial renovation in Laval, Montréal and the North Shore. Explore our services and request a free estimate.',alternates:{canonical,languages:{'fr-CA':fr,'en-CA':canonical}}}}
export default async function Page({params}:{params:Promise<{path?:string[]}>}){const {path}=await params;const p=resolve(path);if(!p)notFound();const settings=configured()?{...defaults,...(await db().from('records').select('data').eq('kind','settings').limit(1).maybeSingle()).data?.data}:defaults;return <EnglishSite slug={p.slug} settings={settings}>{p.slug==='blog'?<BlogContent locale="en" slug={p.article}/>:p.slug==='privacy'?<article className="blog-article"><h1>Privacy</h1><div className="blog-prose"><p>MG Pro uses the contact details, project information and photos you provide to respond to your request, prepare an estimate and follow your project.</p><h2>Your project information</h2><p>Your file may contain contact information, the project address, visit notes, dimensions, photographs, messages, estimates and invoices. Access is restricted to authorized people according to their role.</p><h2>Address suggestions and appointments</h2><p>When you type an address, the search text is sent to Natural Resources Canada to provide suggestions. You can also enter your address manually. If you follow a Calendly link, the appointment is arranged on Calendly under its own privacy terms.</p><h2>Your requests</h2><p>To request access, a correction or deletion of information that no longer needs to be retained, contact <a href="mailto:info@renovationsmgpro.com">info@renovationsmgpro.com</a>.</p><h2>How the site works</h2><p>Technical cookies maintain your signed-in session. Requests are saved directly in our system rather than sent to Typeform. This version has no advertising trackers. The service uses Vercel hosting and Supabase for account and document storage. Retention arrangements will be finalized before the client service launches.</p></div></article>:undefined}</EnglishSite>}
